### ISSUE TITLE
Typo on updateUser method in Docs

### ISSUE THREAD

**Issue by jordanlittle** [smallbets/userbase-homepage#40]
This page:
https://userbase.com/docs/sdk/update-user/

Has a busted `<li>` tag on the error string `ProfileValueCannotBeBlank`.

Loving the product so far. Looking forward to social logins eventually.

**Comment by j-berman** [comment]
[Fixed](https://github.com/smallbets/userbase-homepage/commit/149f7d690817e6f54ece19c2398d2758c477977a)! Thank you!
